## 1. Exploração inicial dos dados

In [40]:
import pandas as pd
df = pd.read_csv("Electric_Vehicle_Population_Data.csv")
df.shape
df.info()
df.isnull().sum()
df.describe(include='all')
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177866 entries, 0 to 177865
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         177866 non-null  object
 1   County                                             177861 non-null  object
 2   City                                               177861 non-null  object
 3   State                                              177866 non-null  object
 4   Postal Code                                        177861 non-null  float64
 5   Model Year                                         177866 non-null  int64
 6   Make                                               177866 non-null  object
 7   Model                                              177866 non-null  object
 8   Electric Vehicle Type                              177866 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  177866 non-null  object
 10  Electric Range                                     177866 non-null  int64
 11  Base MSRP                                          177866 non-null  int64
 12  Legislative District                               177477 non-null  float64
 13  DOL Vehicle ID                                     177866 non-null  int64
 14  Vehicle Location                                   177857 non-null  object
 15  Electric Utility                                   177861 non-null  object
 16  2020 Census Tract                                  177861 non-null  float64
dtypes: float64(3), int64(4), object(10)
memory usage: 23.1+ MB

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJYGDEE1L,King,Seattle,WA,98122.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,37.0,125701579,POINT (-122.30839 47.610365),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,7SAYGDEE9P,Snohomish,Bothell,WA,98021.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1.0,244285107,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,5.306105e+10
2,5YJSA1E4XK,King,Seattle,WA,98109.0,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,36.0,156773144,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5YJSA1E27G,King,Issaquah,WA,98027.0,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,5.0,165103011,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,5YJYGDEE5M,Kitsap,Suquamish,WA,98392.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23.0,205138552,POINT (-122.55717 47.733415),PUGET SOUND ENERGY INC,5.303594e+10

In [42]:
df['Make'].unique()

array(['TESLA', 'FORD', 'NISSAN', 'KIA', 'BMW', 'CHEVROLET', 'AUDI',
       'SMART', 'VOLKSWAGEN', 'TOYOTA', 'RIVIAN', 'JEEP', 'HYUNDAI',
       'FIAT', 'PORSCHE', 'CHRYSLER', 'HONDA', 'MITSUBISHI', 'LEXUS',
       'VOLVO', 'DODGE', 'MERCEDES-BENZ', 'SUBARU', 'JAGUAR', 'POLESTAR',
       'MINI', 'LUCID', 'LAND ROVER', 'CADILLAC', 'ALFA ROMEO', 'FISKER',
       'MAZDA', 'LINCOLN', 'GENESIS', 'TH!NK', 'GMC', 'BENTLEY',
       'AZURE DYNAMICS', 'WHEEGO ELECTRIC CARS', 'ROLLS ROYCE'],
      dtype=object)

In [43]:
df['Model'].unique()

array(['MODEL Y', 'MODEL S', 'FUSION', 'LEAF', 'OPTIMA', 'X5', 'I3',
       'BOLT EV', 'Q5 E', 'MODEL 3', 'C-MAX', 'NIRO', 'E-TRON', 'SOUL EV',
       'I8', 'EV9', 'FORTWO', 'SORENTO', 'E-GOLF', 'PRIUS PRIME', 'R1T',
       'RAV4', 'WRANGLER', 'KONA', 'X3', 'SOUL', 'MODEL X', '500',
       'RAV4 PRIME', 'IONIQ', 'ESCAPE', 'CAYENNE', 'R1S', 'VOLT',
       'SANTA FE', '330E', 'F-150', 'SPARK', 'TUCSON', 'PACIFICA',
       'CLARITY', 'A3', 'OUTLANDER', 'NX', 'EQ FORTWO', 'MUSTANG MACH-E',
       'ID.4', 'EDV', 'XC40', 'HORNET', 'SPORTAGE', 'XC60',
       'EQS-CLASS SUV', 'PRIUS PLUG-IN', 'SOLTERRA', 'EV6', 'GLE-CLASS',
       'I4', 'BOLT EUV', 'Q4', 'XC90', 'KONA ELECTRIC', 'I-PACE', 'PS2',
       'IONIQ 5', 'TAYCAN', 'HARDTOP', 'GRAND CHEROKEE', 'AIR',
       'GLC-CLASS', 'I-MIEV', 'RANGE ROVER SPORT', 'IONIQ 6', 'PRIUS',
       'BZ4X', 'EQS-CLASS SEDAN', 'C40', 'E-TRON SPORTBACK', 'LYRIQ',
       'TONALE', 'I5', '530E', 'ARIYA', 'EQE-CLASS SUV', 'IX',
       'CROSSTREK', '745E', 'RS E-TRON GT', 'OCEAN', 'Q5', 'FOCUS',
       'EQB-CLASS', 'ACCORD', 'V60', 'CX-90', 'TRANSIT', 'E-TRON GT',
       'S60', 'B-CLASS', 'COUNTRYMAN', 'KARMA', 'BLAZER EV', 'Q8',
       'RZ 450E', 'AVIATOR', 'GV60', 'ELR', 'PANAMERA', 'CITY', '740E',
       'EQE-CLASS SEDAN', 'SILVERADO EV', 'FORTWO ELECTRIC DRIVE',
       'CORSAIR', 'HUMMER EV PICKUP', 'RANGE ROVER', 'GV70', 'RANGER',
       'ROADSTER', 'I7', 'G80', 'C-CLASS', 'S90', 'SONATA', 'A7',
       'FLYING SPUR', 'A8 E', 'XM', 'MX-30', 'S-CLASS',
       'TRANSIT CONNECT ELECTRIC', 'CT6', 'SQ8', '918', 'WHEEGO', '745LE',
       'S-10 PICKUP', 'SPECTRE', 'BENTAYGA'], dtype=object)

In [44]:
df['DOL Vehicle ID'].nunique()

177866

## 2. Identificação de problemas de qualidade

In [45]:
df[df['County'].isnull()]  # ver se são as mesmas 5 linhas em todas as colunas relacionadas a localização

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
149245,5YJSA1E21J,NaN,NaN,AE,NaN,2018,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,249,0,NaN,220643132,NaN,NaN,NaN
154553,5YJ3E1EA5K,NaN,NaN,BC,NaN,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,NaN,475254825,NaN,NaN,NaN
159157,5YJRE11B48,NaN,NaN,BC,NaN,2008,TESLA,ROADSTER,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,98950,NaN,143609049,NaN,NaN,NaN
167298,5YJXCAE24H,NaN,NaN,BC,NaN,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200,0,NaN,159850029,NaN,NaN,NaN
170413,1N4AZ0CP1D,NaN,NaN,AP,NaN,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75,0,NaN,112277063,NaN,NaN,NaN

In [47]:
df['Base MSRP'].value_counts().head()

Base MSRP
0        174522
69900      1370
31950       381
52900       222
32250       136
Name: count, dtype: int64

In [48]:
df['Legislative District'].isnull().sum()
df[df['Legislative District'].isnull()][['State', 'County']].value_counts()

State  County
CA     San Diego      24
VA     Fairfax        13
CA     Orange         10
       Santa Clara     9
       Los Angeles     8
                      ..
IL     Champaign       1
ID     Kootenai        1
IA     Marion          1
HI     Maui            1
WY     Sheridan        1
Name: count, Length: 174, dtype: int64

In [30]:
len(df[df['County'].isnull()])
df[df['County'].isnull()]['State'].value_counts()

State
BC    3
AE    1
AP    1
Name: count, dtype: int64

In [46]:
df['Electric Range'].eq(0).sum()

np.int64(91950)

In [29]:
df[df['Electric Range'] == 0]['Electric Vehicle Type'].value_counts()

Electric Vehicle Type
Battery Electric Vehicle (BEV)    91950
Name: count, dtype: int64

## 3. Tratamento e limpeza

In [31]:
df = df.dropna(subset=['County'])

In [33]:
df = df.rename(columns={
    'VIN (1-10)': 'vin_prefix',
    'County': 'county',
    'City': 'city',
    'State': 'state',
    'Postal Code': 'postal_code',
    'Model Year': 'model_year',
    'Make': 'make',
    'Model': 'model',
    'Electric Vehicle Type': 'electric_vehicle_type',
    'Clean Alternative Fuel Vehicle (CAFV) Eligibility': 'cafv_eligibility',
    'Electric Range': 'electric_range',
    'Base MSRP': 'base_msrp',
    'Legislative District': 'legislative_district',
    'DOL Vehicle ID': 'vehicle_id',
    'Vehicle Location': 'vehicle_location',
    'Electric Utility': 'electric_utility',
    '2020 Census Tract': 'census_tract_2020'
})

In [34]:
df.columns

Index(['vin_prefix', 'county', 'city', 'state', 'postal_code', 'model_year',
       'make', 'model', 'electric_vehicle_type', 'cafv_eligibility',
       'electric_range', 'base_msrp', 'legislative_district', 'vehicle_id',
       'vehicle_location', 'electric_utility', 'census_tract_2020'],
      dtype='object')

## 4. Exportação

In [35]:
df.to_csv('ev_data_limpo.csv', index=False)